apiVersion: v1
kind: Pod
metadata:
  labels:
    app: tripleo-step-tripleo_step3
  name: tripleo_step3-step-4
spec:
  containers:
  - command: &id001
    - /bin/bash
    - -c
    - /usr/local/bin/kolla_set_configs && /usr/sbin/crond -n
    env:
    - name: KOLLA_CONFIG_STRATEGY
      value: COPY_ALWAYS
    - name: TRIPLEO_CONFIG_HASH
      value: 9cb76b3e64a1db57a5ebca60a5378358
    image: 192.168.24.1:8787/tripleomaster/openstack-keystone:2fa7870e5aa16053f63f8b63df4f955b-updated-20210901075107
    label:
      config_data:
        command: *id001
        environment:
          KOLLA_CONFIG_STRATEGY: COPY_ALWAYS
          TRIPLEO_CONFIG_HASH: 9cb76b3e64a1db57a5ebca60a5378358
        healthcheck:
          test: /usr/share/openstack-tripleo-common/healthcheck/cron keystone
        image: 192.168.24.1:8787/tripleomaster/openstack-keystone:2fa7870e5aa16053f63f8b63df4f955b-updated-20210901075107
        net: host
        privileged: false
        restart: always
        start_order: 4
        user: root
        volumes:
        - /etc/hosts:/etc/hosts:ro
        - /etc/localtime:/etc/localtime:ro
        - /etc/pki/ca-trust/extracted:/etc/pki/ca-trust/extracted:ro
        - /etc/pki/ca-trust/source/anchors:/etc/pki/ca-trust/source/anchors:ro
        - /etc/pki/tls/certs/ca-bundle.crt:/etc/pki/tls/certs/ca-bundle.crt:ro
        - /etc/pki/tls/certs/ca-bundle.trust.crt:/etc/pki/tls/certs/ca-bundle.trust.crt:ro
        - /etc/pki/tls/cert.pem:/etc/pki/tls/cert.pem:ro
        - /dev/log:/dev/log
        - /etc/puppet:/etc/puppet:ro
        - /var/log/containers/keystone:/var/log/keystone:z
        - /var/log/containers/httpd/keystone:/var/log/httpd:z
        - /var/lib/kolla/config_files/keystone_cron.json:/var/lib/kolla/config_files/config.json:ro
        - /var/lib/config-data/puppet-generated/keystone/:/var/lib/kolla/config_files/src:ro
      config_id: tripleo_step3
      container_name: keystone_cron
      managed_by: tripleo_ansible
    name: keystone_cron
    securityContext:
      allowPrivilegeEscalation: false
      runAsGroup: 0
      runAsUser: 0
    volumeMounts:
    - mountPath: /etc/hosts
      name: _etc_hosts___etc_hosts
      readOnly: true
    - mountPath: /etc/localtime
      name: _etc_localtime___etc_localtime
      readOnly: true
    - mountPath: /etc/pki/ca-trust/extracted
      name: _etc_pki_ca-trust_extracted___etc_pki_ca-trust_extracted
      readOnly: true
    - mountPath: /etc/pki/ca-trust/source/anchors
      name: _etc_pki_ca-trust_source_anchors___etc_pki_ca-trust_source_anchors
      readOnly: true
    - mountPath: /etc/pki/tls/certs/ca-bundle.crt
      name: _etc_pki_tls_certs_ca-bundle.crt___etc_pki_tls_certs_ca-bundle.crt
      readOnly: true
    - mountPath: /etc/pki/tls/certs/ca-bundle.trust.crt
      name: _etc_pki_tls_certs_ca-bundle.trust.crt___etc_pki_tls_certs_ca-bundle.trust.crt
      readOnly: true
    - mountPath: /etc/pki/tls/cert.pem
      name: _etc_pki_tls_cert.pem___etc_pki_tls_cert.pem
      readOnly: true
    - mountPath: /dev/log
      name: _dev_log___dev_log
    - mountPath: /etc/puppet
      name: _etc_puppet___etc_puppet
      readOnly: true
    - mountPath: /var/log/keystone
      name: _var_log_containers_keystone___var_log_keystone
    - mountPath: /var/log/httpd
      name: _var_log_containers_httpd_keystone___var_log_httpd
    - mountPath: /var/lib/kolla/config_files/config.json
      name: _var_lib_kolla_config_files_keystone_cron.json___var_lib_kolla_config_files_config.json
      readOnly: true
    - mountPath: /var/lib/kolla/config_files/src
      name: _var_lib_config-data_puppet-generated_keystone___var_lib_kolla_config_files_src
      readOnly: true
  hostNetwork: true
  restartPolicy: Always
  volumes:
  - hostPath:
      path: /etc/hosts
    name: _etc_hosts___etc_hosts
  - hostPath:
      path: /etc/localtime
    name: _etc_localtime___etc_localtime
  - hostPath:
      path: /etc/pki/ca-trust/extracted
    name: _etc_pki_ca-trust_extracted___etc_pki_ca-trust_extracted
  - hostPath:
      path: /etc/pki/ca-trust/source/anchors
    name: _etc_pki_ca-trust_source_anchors___etc_pki_ca-trust_source_anchors
  - hostPath:
      path: /etc/pki/tls/certs/ca-bundle.crt
    name: _etc_pki_tls_certs_ca-bundle.crt___etc_pki_tls_certs_ca-bundle.crt
  - hostPath:
      path: /etc/pki/tls/certs/ca-bundle.trust.crt
    name: _etc_pki_tls_certs_ca-bundle.trust.crt___etc_pki_tls_certs_ca-bundle.trust.crt
  - hostPath:
      path: /etc/pki/tls/cert.pem
    name: _etc_pki_tls_cert.pem___etc_pki_tls_cert.pem
  - hostPath:
      path: /dev/log
    name: _dev_log___dev_log
  - hostPath:
      path: /etc/puppet
    name: _etc_puppet___etc_puppet
  - hostPath:
      path: /var/log/containers/keystone
    name: _var_log_containers_keystone___var_log_keystone
  - hostPath:
      path: /var/log/containers/httpd/keystone
    name: _var_log_containers_httpd_keystone___var_log_httpd
  - hostPath:
      path: /var/lib/kolla/config_files/keystone_cron.json
    name: _var_lib_kolla_config_files_keystone_cron.json___var_lib_kolla_config_files_config.json
  - hostPath:
      path: /var/lib/config-data/puppet-generated/keystone
    name: _var_lib_config-data_puppet-generated_keystone___var_lib_kolla_config_files_src
