apiVersion: v1
kind: Pod
metadata:
  labels:
    app: tripleo-step-tripleo_step1
  name: tripleo_step1-temp-step-0
spec:
  containers:
  - command: &id001
    - /bin/bash
    - -c
    - chown -R mysql:mysql /var/log/mariadb /var/lib/mysql
    image: 192.168.24.1:8787/tripleomaster/openstack-mariadb:2fa7870e5aa16053f63f8b63df4f955b-updated-20210901075107
    label:
      config_data:
        command: *id001
        image: 192.168.24.1:8787/tripleomaster/openstack-mariadb:2fa7870e5aa16053f63f8b63df4f955b-updated-20210901075107
        net: none
        privileged: false
        user: root
        volumes:
        - /var/log/containers/mysql:/var/log/mariadb:z
        - /var/lib/mysql:/var/lib/mysql:z
      config_id: tripleo_step1
      container_name: mysql_init_logs
      managed_by: tripleo_ansible
      temporary: true
    name: mysql_init_logs
    securityContext:
      allowPrivilegeEscalation: false
      runAsGroup: 0
      runAsUser: 0
    volumeMounts:
    - mountPath: /var/log/mariadb
      name: _var_log_containers_mysql___var_log_mariadb
    - mountPath: /var/lib/mysql
      name: _var_lib_mysql___var_lib_mysql
  - command: &id002
    - /bin/bash
    - -c
    - chown -R rabbitmq:rabbitmq /var/log/rabbitmq
    image: 192.168.24.1:8787/tripleomaster/openstack-rabbitmq:2fa7870e5aa16053f63f8b63df4f955b-updated-20210901075107
    label:
      config_data:
        command: *id002
        detach: false
        image: 192.168.24.1:8787/tripleomaster/openstack-rabbitmq:2fa7870e5aa16053f63f8b63df4f955b-updated-20210901075107
        net: none
        privileged: false
        start_order: 0
        user: root
        volumes:
        - /var/log/containers/rabbitmq:/var/log/rabbitmq:z
      config_id: tripleo_step1
      container_name: rabbitmq_init_logs
      managed_by: tripleo_ansible
      temporary: true
    name: rabbitmq_init_logs
    securityContext:
      allowPrivilegeEscalation: false
      runAsGroup: 0
      runAsUser: 0
    volumeMounts:
    - mountPath: /var/log/rabbitmq
      name: _var_log_containers_rabbitmq___var_log_rabbitmq
  hostNetwork: true
  restartPolicy: Never
  volumes:
  - hostPath:
      path: /var/log/containers/mysql
    name: _var_log_containers_mysql___var_log_mariadb
  - hostPath:
      path: /var/lib/mysql
    name: _var_lib_mysql___var_lib_mysql
  - hostPath:
      path: /var/log/containers/rabbitmq
    name: _var_log_containers_rabbitmq___var_log_rabbitmq
