apiVersion: v1
kind: Pod
metadata:
  labels:
    app: tripleo-step-tripleo_step3
  name: tripleo_step3-temp-step-1
spec:
  containers:
  - command: &id001
    - /bin/bash
    - -c
    - chown -R ironic-inspector:ironic-inspector /var/lib/ironic-inspector/dhcp-hostsdir
    image: 192.168.24.1:8787/tripleomaster/openstack-ironic-inspector:2fa7870e5aa16053f63f8b63df4f955b-updated-20210901075107
    label:
      config_data:
        command: *id001
        image: 192.168.24.1:8787/tripleomaster/openstack-ironic-inspector:2fa7870e5aa16053f63f8b63df4f955b-updated-20210901075107
        net: none
        start_order: 1
        user: root
        volumes:
        - /var/lib/ironic-inspector/dhcp-hostsdir:/var/lib/ironic-inspector/dhcp-hostsdir:shared,z
      config_id: tripleo_step3
      container_name: ironic_inspector_init_dnsmasq_dhcp_hostsdir
      managed_by: tripleo_ansible
      temporary: true
    name: ironic_inspector_init_dnsmasq_dhcp_hostsdir
    securityContext:
      runAsGroup: 0
      runAsUser: 0
    volumeMounts:
    - mountPath: /var/lib/ironic-inspector/dhcp-hostsdir
      name: _var_lib_ironic-inspector_dhcp-hostsdir___var_lib_ironic-inspector_dhcp-hostsdir
  - env:
    - name: KOLLA_CONFIG_STRATEGY
      value: COPY_ALWAYS
    - name: TRIPLEO_DEPLOY_IDENTIFIER
      value: '1630483989'
    - name: TRIPLEO_CONFIG_HASH
      value: 331566284ca2479bc1d8b7b78a02e844
    image: 192.168.24.1:8787/tripleomaster/openstack-ironic-api:2fa7870e5aa16053f63f8b63df4f955b-updated-20210901075107
    label:
      config_data:
        detach: false
        environment:
          KOLLA_CONFIG_STRATEGY: COPY_ALWAYS
          TRIPLEO_CONFIG_HASH: 331566284ca2479bc1d8b7b78a02e844
          TRIPLEO_DEPLOY_IDENTIFIER: '1630483989'
        image: 192.168.24.1:8787/tripleomaster/openstack-ironic-api:2fa7870e5aa16053f63f8b63df4f955b-updated-20210901075107
        net: host
        privileged: false
        start_order: 1
        user: root
        volumes:
        - /etc/hosts:/etc/hosts:ro
        - /etc/localtime:/etc/localtime:ro
        - /etc/pki/ca-trust/extracted:/etc/pki/ca-trust/extracted:ro
        - /etc/pki/ca-trust/source/anchors:/etc/pki/ca-trust/source/anchors:ro
        - /etc/pki/tls/certs/ca-bundle.crt:/etc/pki/tls/certs/ca-bundle.crt:ro
        - /etc/pki/tls/certs/ca-bundle.trust.crt:/etc/pki/tls/certs/ca-bundle.trust.crt:ro
        - /etc/pki/tls/cert.pem:/etc/pki/tls/cert.pem:ro
        - /dev/log:/dev/log
        - /etc/puppet:/etc/puppet:ro
        - /var/lib/kolla/config_files/ironic_api_db_sync.json:/var/lib/kolla/config_files/config.json:ro
        - /var/lib/config-data/puppet-generated/ironic_api:/var/lib/kolla/config_files/src:ro
        - /var/log/containers/ironic:/var/log/ironic:z
      config_id: tripleo_step3
      container_name: ironic_db_sync
      managed_by: tripleo_ansible
      temporary: true
    name: ironic_db_sync
    securityContext:
      allowPrivilegeEscalation: false
      runAsGroup: 0
      runAsUser: 0
    volumeMounts:
    - mountPath: /etc/hosts
      name: _etc_hosts___etc_hosts
      readOnly: true
    - mountPath: /etc/localtime
      name: _etc_localtime___etc_localtime
      readOnly: true
    - mountPath: /etc/pki/ca-trust/extracted
      name: _etc_pki_ca-trust_extracted___etc_pki_ca-trust_extracted
      readOnly: true
    - mountPath: /etc/pki/ca-trust/source/anchors
      name: _etc_pki_ca-trust_source_anchors___etc_pki_ca-trust_source_anchors
      readOnly: true
    - mountPath: /etc/pki/tls/certs/ca-bundle.crt
      name: _etc_pki_tls_certs_ca-bundle.crt___etc_pki_tls_certs_ca-bundle.crt
      readOnly: true
    - mountPath: /etc/pki/tls/certs/ca-bundle.trust.crt
      name: _etc_pki_tls_certs_ca-bundle.trust.crt___etc_pki_tls_certs_ca-bundle.trust.crt
      readOnly: true
    - mountPath: /etc/pki/tls/cert.pem
      name: _etc_pki_tls_cert.pem___etc_pki_tls_cert.pem
      readOnly: true
    - mountPath: /dev/log
      name: _dev_log___dev_log
    - mountPath: /etc/puppet
      name: _etc_puppet___etc_puppet
      readOnly: true
    - mountPath: /var/lib/kolla/config_files/config.json
      name: _var_lib_kolla_config_files_ironic_api_db_sync.json___var_lib_kolla_config_files_config.json
      readOnly: true
    - mountPath: /var/lib/kolla/config_files/src
      name: _var_lib_config-data_puppet-generated_ironic_api___var_lib_kolla_config_files_src
      readOnly: true
    - mountPath: /var/log/ironic
      name: _var_log_containers_ironic___var_log_ironic
  hostNetwork: true
  restartPolicy: Never
  volumes:
  - hostPath:
      path: /var/lib/ironic-inspector/dhcp-hostsdir
    name: _var_lib_ironic-inspector_dhcp-hostsdir___var_lib_ironic-inspector_dhcp-hostsdir
  - hostPath:
      path: /etc/hosts
    name: _etc_hosts___etc_hosts
  - hostPath:
      path: /etc/localtime
    name: _etc_localtime___etc_localtime
  - hostPath:
      path: /etc/pki/ca-trust/extracted
    name: _etc_pki_ca-trust_extracted___etc_pki_ca-trust_extracted
  - hostPath:
      path: /etc/pki/ca-trust/source/anchors
    name: _etc_pki_ca-trust_source_anchors___etc_pki_ca-trust_source_anchors
  - hostPath:
      path: /etc/pki/tls/certs/ca-bundle.crt
    name: _etc_pki_tls_certs_ca-bundle.crt___etc_pki_tls_certs_ca-bundle.crt
  - hostPath:
      path: /etc/pki/tls/certs/ca-bundle.trust.crt
    name: _etc_pki_tls_certs_ca-bundle.trust.crt___etc_pki_tls_certs_ca-bundle.trust.crt
  - hostPath:
      path: /etc/pki/tls/cert.pem
    name: _etc_pki_tls_cert.pem___etc_pki_tls_cert.pem
  - hostPath:
      path: /dev/log
    name: _dev_log___dev_log
  - hostPath:
      path: /etc/puppet
    name: _etc_puppet___etc_puppet
  - hostPath:
      path: /var/lib/kolla/config_files/ironic_api_db_sync.json
    name: _var_lib_kolla_config_files_ironic_api_db_sync.json___var_lib_kolla_config_files_config.json
  - hostPath:
      path: /var/lib/config-data/puppet-generated/ironic_api
    name: _var_lib_config-data_puppet-generated_ironic_api___var_lib_kolla_config_files_src
  - hostPath:
      path: /var/log/containers/ironic
    name: _var_log_containers_ironic___var_log_ironic
