apiVersion: v1
kind: Pod
metadata:
  labels:
    app: tripleo-step-tripleo_step1
  name: tripleo_step1-step-1
spec:
  containers:
  - env:
    - name: KOLLA_CONFIG_STRATEGY
      value: COPY_ALWAYS
    - name: TRIPLEO_CONFIG_HASH
      value: 1a2c077eab8c9463f6bff7587bd296f7
    image: 192.168.24.1:8787/tripleomaster/openstack-haproxy:2fa7870e5aa16053f63f8b63df4f955b-updated-20210901075107
    label:
      config_data:
        environment:
          KOLLA_CONFIG_STRATEGY: COPY_ALWAYS
          TRIPLEO_CONFIG_HASH: 1a2c077eab8c9463f6bff7587bd296f7
        image: 192.168.24.1:8787/tripleomaster/openstack-haproxy:2fa7870e5aa16053f63f8b63df4f955b-updated-20210901075107
        net: host
        restart: always
        security_opt:
        - label=disable
        start_order: 1
        volumes:
        - /etc/hosts:/etc/hosts:ro
        - /etc/localtime:/etc/localtime:ro
        - /etc/pki/ca-trust/extracted:/etc/pki/ca-trust/extracted:ro
        - /etc/pki/ca-trust/source/anchors:/etc/pki/ca-trust/source/anchors:ro
        - /etc/pki/tls/certs/ca-bundle.crt:/etc/pki/tls/certs/ca-bundle.crt:ro
        - /etc/pki/tls/certs/ca-bundle.trust.crt:/etc/pki/tls/certs/ca-bundle.trust.crt:ro
        - /etc/pki/tls/cert.pem:/etc/pki/tls/cert.pem:ro
        - /dev/log:/dev/log
        - /etc/puppet:/etc/puppet:ro
        - /var/lib/kolla/config_files/haproxy.json:/var/lib/kolla/config_files/config.json:ro
        - /var/lib/config-data/puppet-generated/haproxy:/var/lib/kolla/config_files/src:ro
        - /var/lib/haproxy:/var/lib/haproxy:rw,z
        - /etc/pki/tls/private/overcloud_endpoint.pem:/var/lib/kolla/config_files/src-tls//etc/pki/tls/private/overcloud_endpoint.pem:ro,shared
      config_id: tripleo_step1
      container_name: haproxy
      managed_by: tripleo_ansible
    name: haproxy
    volumeMounts:
    - mountPath: /etc/hosts
      name: _etc_hosts___etc_hosts
      readOnly: true
    - mountPath: /etc/localtime
      name: _etc_localtime___etc_localtime
      readOnly: true
    - mountPath: /etc/pki/ca-trust/extracted
      name: _etc_pki_ca-trust_extracted___etc_pki_ca-trust_extracted
      readOnly: true
    - mountPath: /etc/pki/ca-trust/source/anchors
      name: _etc_pki_ca-trust_source_anchors___etc_pki_ca-trust_source_anchors
      readOnly: true
    - mountPath: /etc/pki/tls/certs/ca-bundle.crt
      name: _etc_pki_tls_certs_ca-bundle.crt___etc_pki_tls_certs_ca-bundle.crt
      readOnly: true
    - mountPath: /etc/pki/tls/certs/ca-bundle.trust.crt
      name: _etc_pki_tls_certs_ca-bundle.trust.crt___etc_pki_tls_certs_ca-bundle.trust.crt
      readOnly: true
    - mountPath: /etc/pki/tls/cert.pem
      name: _etc_pki_tls_cert.pem___etc_pki_tls_cert.pem
      readOnly: true
    - mountPath: /dev/log
      name: _dev_log___dev_log
    - mountPath: /etc/puppet
      name: _etc_puppet___etc_puppet
      readOnly: true
    - mountPath: /var/lib/kolla/config_files/config.json
      name: _var_lib_kolla_config_files_haproxy.json___var_lib_kolla_config_files_config.json
      readOnly: true
    - mountPath: /var/lib/kolla/config_files/src
      name: _var_lib_config-data_puppet-generated_haproxy___var_lib_kolla_config_files_src
      readOnly: true
    - mountPath: /var/lib/haproxy
      name: _var_lib_haproxy___var_lib_haproxy
    - mountPath: /var/lib/kolla/config_files/src-tls//etc/pki/tls/private/overcloud_endpoint.pem
      name: _etc_pki_tls_private_overcloud_endpoint.pem___var_lib_kolla_config_files_src-tls__etc_pki_tls_private_overcloud_endpoint.pem
      readOnly: true
  hostNetwork: true
  restartPolicy: Always
  volumes:
  - hostPath:
      path: /etc/hosts
    name: _etc_hosts___etc_hosts
  - hostPath:
      path: /etc/localtime
    name: _etc_localtime___etc_localtime
  - hostPath:
      path: /etc/pki/ca-trust/extracted
    name: _etc_pki_ca-trust_extracted___etc_pki_ca-trust_extracted
  - hostPath:
      path: /etc/pki/ca-trust/source/anchors
    name: _etc_pki_ca-trust_source_anchors___etc_pki_ca-trust_source_anchors
  - hostPath:
      path: /etc/pki/tls/certs/ca-bundle.crt
    name: _etc_pki_tls_certs_ca-bundle.crt___etc_pki_tls_certs_ca-bundle.crt
  - hostPath:
      path: /etc/pki/tls/certs/ca-bundle.trust.crt
    name: _etc_pki_tls_certs_ca-bundle.trust.crt___etc_pki_tls_certs_ca-bundle.trust.crt
  - hostPath:
      path: /etc/pki/tls/cert.pem
    name: _etc_pki_tls_cert.pem___etc_pki_tls_cert.pem
  - hostPath:
      path: /dev/log
    name: _dev_log___dev_log
  - hostPath:
      path: /etc/puppet
    name: _etc_puppet___etc_puppet
  - hostPath:
      path: /var/lib/kolla/config_files/haproxy.json
    name: _var_lib_kolla_config_files_haproxy.json___var_lib_kolla_config_files_config.json
  - hostPath:
      path: /var/lib/config-data/puppet-generated/haproxy
    name: _var_lib_config-data_puppet-generated_haproxy___var_lib_kolla_config_files_src
  - hostPath:
      path: /var/lib/haproxy
    name: _var_lib_haproxy___var_lib_haproxy
  - hostPath:
      path: /etc/pki/tls/private/overcloud_endpoint.pem
    name: _etc_pki_tls_private_overcloud_endpoint.pem___var_lib_kolla_config_files_src-tls__etc_pki_tls_private_overcloud_endpoint.pem
