apiVersion: v1
kind: Pod
metadata:
  labels:
    app: tripleo-step-tripleo_step2
  name: tripleo_step2-temp-step-0
spec:
  containers:
  - command: &id001
    - /bin/bash
    - -c
    - chown -R ironic:ironic /var/log/ironic
    image: 192.168.24.1:8787/tripleomaster/openstack-ironic-api:2fa7870e5aa16053f63f8b63df4f955b-updated-20210901075107
    label:
      config_data:
        command: *id001
        image: 192.168.24.1:8787/tripleomaster/openstack-ironic-api:2fa7870e5aa16053f63f8b63df4f955b-updated-20210901075107
        net: none
        privileged: false
        user: root
        volumes:
        - /var/log/containers/ironic:/var/log/ironic:z
        - /var/log/containers/httpd/ironic-api:/var/log/httpd:z
      config_id: tripleo_step2
      container_name: ironic_init_logs
      managed_by: tripleo_ansible
      temporary: true
    name: ironic_init_logs
    securityContext:
      allowPrivilegeEscalation: false
      runAsGroup: 0
      runAsUser: 0
    volumeMounts:
    - mountPath: /var/log/ironic
      name: _var_log_containers_ironic___var_log_ironic
    - mountPath: /var/log/httpd
      name: _var_log_containers_httpd_ironic-api___var_log_httpd
  - command: &id002
    - /bin/bash
    - -c
    - chown -R neutron:neutron /var/log/neutron
    image: 192.168.24.1:8787/tripleomaster/openstack-neutron-server:2fa7870e5aa16053f63f8b63df4f955b-updated-20210901075107
    label:
      config_data:
        command: *id002
        image: 192.168.24.1:8787/tripleomaster/openstack-neutron-server:2fa7870e5aa16053f63f8b63df4f955b-updated-20210901075107
        net: none
        privileged: false
        user: root
        volumes:
        - /var/log/containers/neutron:/var/log/neutron:z
        - /var/log/containers/httpd/neutron-api:/var/log/httpd:z
      config_id: tripleo_step2
      container_name: neutron_init_logs
      managed_by: tripleo_ansible
      temporary: true
    name: neutron_init_logs
    securityContext:
      allowPrivilegeEscalation: false
      runAsGroup: 0
      runAsUser: 0
    volumeMounts:
    - mountPath: /var/log/neutron
      name: _var_log_containers_neutron___var_log_neutron
    - mountPath: /var/log/httpd
      name: _var_log_containers_httpd_neutron-api___var_log_httpd
  hostNetwork: true
  restartPolicy: Never
  volumes:
  - hostPath:
      path: /var/log/containers/ironic
    name: _var_log_containers_ironic___var_log_ironic
  - hostPath:
      path: /var/log/containers/httpd/ironic-api
    name: _var_log_containers_httpd_ironic-api___var_log_httpd
  - hostPath:
      path: /var/log/containers/neutron
    name: _var_log_containers_neutron___var_log_neutron
  - hostPath:
      path: /var/log/containers/httpd/neutron-api
    name: _var_log_containers_httpd_neutron-api___var_log_httpd
