apiVersion: v1
kind: Pod
metadata:
  labels:
    app: tripleo-step-tripleo_step2
  name: tripleo_step2-temp-step-3
spec:
  containers:
  - command: &id001
    - /container-config-scripts/mysql_upgrade_db.sh
    env:
    - name: KOLLA_CONFIG_STRATEGY
      value: COPY_ALWAYS
    - name: TRIPLEO_CONFIG_HASH
      value: f7aee8d91a3d2893347665dd9b977e70-f7aee8d91a3d2893347665dd9b977e70
    image: 192.168.24.1:8787/tripleomaster/openstack-mariadb:2fa7870e5aa16053f63f8b63df4f955b-updated-20210901075107
    label:
      config_data:
        command: *id001
        config_volume: mysql
        detach: false
        environment:
          KOLLA_CONFIG_STRATEGY: COPY_ALWAYS
          TRIPLEO_CONFIG_HASH: f7aee8d91a3d2893347665dd9b977e70-f7aee8d91a3d2893347665dd9b977e70
        image: 192.168.24.1:8787/tripleomaster/openstack-mariadb:2fa7870e5aa16053f63f8b63df4f955b-updated-20210901075107
        net: host
        start_order: 3
        user: root
        volumes:
        - /var/lib/kolla/config_files/mysql.json:/var/lib/kolla/config_files/config.json
        - /var/lib/config-data/puppet-generated/mysql:/var/lib/kolla/config_files/src:ro
        - /etc/localtime:/etc/localtime:ro
        - /etc/hosts:/etc/hosts:ro
        - /var/lib/mysql:/var/lib/mysql
        - /var/log/containers/mysql:/var/log/mariadb
        - /var/lib/config-data/puppet-generated/mysql/root:/root:rw
        - /var/lib/container-config-scripts/:/container-config-scripts/:ro
      config_id: tripleo_step2
      container_name: mysql_upgrade_db
      managed_by: tripleo_ansible
      temporary: true
    name: mysql_upgrade_db
    securityContext:
      runAsGroup: 0
      runAsUser: 0
    volumeMounts:
    - mountPath: /var/lib/kolla/config_files/config.json
      name: _var_lib_kolla_config_files_mysql.json___var_lib_kolla_config_files_config.json
    - mountPath: /var/lib/kolla/config_files/src
      name: _var_lib_config-data_puppet-generated_mysql___var_lib_kolla_config_files_src
      readOnly: true
    - mountPath: /etc/localtime
      name: _etc_localtime___etc_localtime
      readOnly: true
    - mountPath: /etc/hosts
      name: _etc_hosts___etc_hosts
      readOnly: true
    - mountPath: /var/lib/mysql
      name: _var_lib_mysql___var_lib_mysql
    - mountPath: /var/log/mariadb
      name: _var_log_containers_mysql___var_log_mariadb
    - mountPath: /root
      name: _var_lib_config-data_puppet-generated_mysql_root___root
    - mountPath: /container-config-scripts
      name: _var_lib_container-config-scripts___container-config-scripts
      readOnly: true
  hostNetwork: true
  restartPolicy: Never
  volumes:
  - hostPath:
      path: /var/lib/kolla/config_files/mysql.json
    name: _var_lib_kolla_config_files_mysql.json___var_lib_kolla_config_files_config.json
  - hostPath:
      path: /var/lib/config-data/puppet-generated/mysql
    name: _var_lib_config-data_puppet-generated_mysql___var_lib_kolla_config_files_src
  - hostPath:
      path: /etc/localtime
    name: _etc_localtime___etc_localtime
  - hostPath:
      path: /etc/hosts
    name: _etc_hosts___etc_hosts
  - hostPath:
      path: /var/lib/mysql
    name: _var_lib_mysql___var_lib_mysql
  - hostPath:
      path: /var/log/containers/mysql
    name: _var_log_containers_mysql___var_log_mariadb
  - hostPath:
      path: /var/lib/config-data/puppet-generated/mysql/root
    name: _var_lib_config-data_puppet-generated_mysql_root___root
  - hostPath:
      path: /var/lib/container-config-scripts
    name: _var_lib_container-config-scripts___container-config-scripts
