apiVersion: v1
kind: Pod
metadata:
  labels:
    app: tripleo-step-tripleo_step3
  name: tripleo_step3-temp-step-0
spec:
  containers:
  - env:
    - name: KOLLA_CONFIG_STRATEGY
      value: COPY_ALWAYS
    - name: TRIPLEO_DEPLOY_IDENTIFIER
      value: '1630483989'
    - name: TRIPLEO_CONFIG_HASH
      value: a196bc498338e13acb71495bbaaddcd6
    image: 192.168.24.1:8787/tripleomaster/openstack-neutron-server:2fa7870e5aa16053f63f8b63df4f955b-updated-20210901075107
    label:
      config_data:
        detach: false
        environment:
          KOLLA_CONFIG_STRATEGY: COPY_ALWAYS
          TRIPLEO_CONFIG_HASH: a196bc498338e13acb71495bbaaddcd6
          TRIPLEO_DEPLOY_IDENTIFIER: '1630483989'
        image: 192.168.24.1:8787/tripleomaster/openstack-neutron-server:2fa7870e5aa16053f63f8b63df4f955b-updated-20210901075107
        net: host
        privileged: false
        user: root
        volumes:
        - /etc/hosts:/etc/hosts:ro
        - /etc/localtime:/etc/localtime:ro
        - /etc/pki/ca-trust/extracted:/etc/pki/ca-trust/extracted:ro
        - /etc/pki/ca-trust/source/anchors:/etc/pki/ca-trust/source/anchors:ro
        - /etc/pki/tls/certs/ca-bundle.crt:/etc/pki/tls/certs/ca-bundle.crt:ro
        - /etc/pki/tls/certs/ca-bundle.trust.crt:/etc/pki/tls/certs/ca-bundle.trust.crt:ro
        - /etc/pki/tls/cert.pem:/etc/pki/tls/cert.pem:ro
        - /dev/log:/dev/log
        - /etc/puppet:/etc/puppet:ro
        - /var/log/containers/neutron:/var/log/neutron:z
        - /var/log/containers/httpd/neutron-api:/var/log/httpd:z
        - /var/lib/kolla/config_files/neutron_api_db_sync.json:/var/lib/kolla/config_files/config.json:ro
        - /var/lib/config-data/puppet-generated/neutron:/var/lib/kolla/config_files/src:ro
      config_id: tripleo_step3
      container_name: neutron_db_sync
      managed_by: tripleo_ansible
      temporary: true
    name: neutron_db_sync
    securityContext:
      allowPrivilegeEscalation: false
      runAsGroup: 0
      runAsUser: 0
    volumeMounts:
    - mountPath: /etc/hosts
      name: _etc_hosts___etc_hosts
      readOnly: true
    - mountPath: /etc/localtime
      name: _etc_localtime___etc_localtime
      readOnly: true
    - mountPath: /etc/pki/ca-trust/extracted
      name: _etc_pki_ca-trust_extracted___etc_pki_ca-trust_extracted
      readOnly: true
    - mountPath: /etc/pki/ca-trust/source/anchors
      name: _etc_pki_ca-trust_source_anchors___etc_pki_ca-trust_source_anchors
      readOnly: true
    - mountPath: /etc/pki/tls/certs/ca-bundle.crt
      name: _etc_pki_tls_certs_ca-bundle.crt___etc_pki_tls_certs_ca-bundle.crt
      readOnly: true
    - mountPath: /etc/pki/tls/certs/ca-bundle.trust.crt
      name: _etc_pki_tls_certs_ca-bundle.trust.crt___etc_pki_tls_certs_ca-bundle.trust.crt
      readOnly: true
    - mountPath: /etc/pki/tls/cert.pem
      name: _etc_pki_tls_cert.pem___etc_pki_tls_cert.pem
      readOnly: true
    - mountPath: /dev/log
      name: _dev_log___dev_log
    - mountPath: /etc/puppet
      name: _etc_puppet___etc_puppet
      readOnly: true
    - mountPath: /var/log/neutron
      name: _var_log_containers_neutron___var_log_neutron
    - mountPath: /var/log/httpd
      name: _var_log_containers_httpd_neutron-api___var_log_httpd
    - mountPath: /var/lib/kolla/config_files/config.json
      name: _var_lib_kolla_config_files_neutron_api_db_sync.json___var_lib_kolla_config_files_config.json
      readOnly: true
    - mountPath: /var/lib/kolla/config_files/src
      name: _var_lib_config-data_puppet-generated_neutron___var_lib_kolla_config_files_src
      readOnly: true
  - command: &id001
    - puppet
    - apply
    - --modulepath
    - /etc/puppet/modules:/usr/share/openstack-puppet/modules
    - --tags
    - file,file_line,concat,augeas,neutron::plugins::ovs::bridge,vs_config
    - -v
    - -e
    - include neutron::agents::ml2::ovs
    env:
    - name: KOLLA_CONFIG_STRATEGY
      value: COPY_ALWAYS
    - name: TRIPLEO_DEPLOY_IDENTIFIER
      value: '1630483989'
    - name: TRIPLEO_CONFIG_HASH
      value: a196bc498338e13acb71495bbaaddcd6
    image: 192.168.24.1:8787/tripleomaster/openstack-neutron-server:2fa7870e5aa16053f63f8b63df4f955b-updated-20210901075107
    label:
      config_data:
        command: *id001
        detach: false
        environment:
          KOLLA_CONFIG_STRATEGY: COPY_ALWAYS
          TRIPLEO_CONFIG_HASH: a196bc498338e13acb71495bbaaddcd6
          TRIPLEO_DEPLOY_IDENTIFIER: '1630483989'
        image: 192.168.24.1:8787/tripleomaster/openstack-neutron-server:2fa7870e5aa16053f63f8b63df4f955b-updated-20210901075107
        net: host
        pid: host
        privileged: true
        security_opt:
        - label=disable
        user: root
        volumes:
        - /etc/hosts:/etc/hosts:ro
        - /etc/localtime:/etc/localtime:ro
        - /etc/pki/ca-trust/extracted:/etc/pki/ca-trust/extracted:ro
        - /etc/pki/ca-trust/source/anchors:/etc/pki/ca-trust/source/anchors:ro
        - /etc/pki/tls/certs/ca-bundle.crt:/etc/pki/tls/certs/ca-bundle.crt:ro
        - /etc/pki/tls/certs/ca-bundle.trust.crt:/etc/pki/tls/certs/ca-bundle.trust.crt:ro
        - /etc/pki/tls/cert.pem:/etc/pki/tls/cert.pem:ro
        - /dev/log:/dev/log
        - /etc/puppet:/etc/puppet:ro
        - /var/lib/kolla/config_files/neutron_ovs_agent.json:/var/lib/kolla/config_files/config.json:ro
        - /var/lib/config-data/puppet-generated/neutron:/var/lib/kolla/config_files/src:ro
        - /lib/modules:/lib/modules:ro
        - /run/openvswitch:/run/openvswitch:shared,z
        - /usr/share/openstack-puppet/modules/:/usr/share/openstack-puppet/modules/:ro
      config_id: tripleo_step3
      container_name: neutron_ovs_bridge
      managed_by: tripleo_ansible
      temporary: true
    name: neutron_ovs_bridge
    securityContext:
      allowPrivilegeEscalation: true
      runAsGroup: 0
      runAsUser: 0
    volumeMounts:
    - mountPath: /etc/hosts
      name: _etc_hosts___etc_hosts
      readOnly: true
    - mountPath: /etc/localtime
      name: _etc_localtime___etc_localtime
      readOnly: true
    - mountPath: /etc/pki/ca-trust/extracted
      name: _etc_pki_ca-trust_extracted___etc_pki_ca-trust_extracted
      readOnly: true
    - mountPath: /etc/pki/ca-trust/source/anchors
      name: _etc_pki_ca-trust_source_anchors___etc_pki_ca-trust_source_anchors
      readOnly: true
    - mountPath: /etc/pki/tls/certs/ca-bundle.crt
      name: _etc_pki_tls_certs_ca-bundle.crt___etc_pki_tls_certs_ca-bundle.crt
      readOnly: true
    - mountPath: /etc/pki/tls/certs/ca-bundle.trust.crt
      name: _etc_pki_tls_certs_ca-bundle.trust.crt___etc_pki_tls_certs_ca-bundle.trust.crt
      readOnly: true
    - mountPath: /etc/pki/tls/cert.pem
      name: _etc_pki_tls_cert.pem___etc_pki_tls_cert.pem
      readOnly: true
    - mountPath: /dev/log
      name: _dev_log___dev_log
    - mountPath: /etc/puppet
      name: _etc_puppet___etc_puppet
      readOnly: true
    - mountPath: /var/lib/kolla/config_files/config.json
      name: _var_lib_kolla_config_files_neutron_ovs_agent.json___var_lib_kolla_config_files_config.json
      readOnly: true
    - mountPath: /var/lib/kolla/config_files/src
      name: _var_lib_config-data_puppet-generated_neutron___var_lib_kolla_config_files_src
      readOnly: true
    - mountPath: /lib/modules
      name: _lib_modules___lib_modules
      readOnly: true
    - mountPath: /run/openvswitch
      name: _run_openvswitch___run_openvswitch
    - mountPath: /usr/share/openstack-puppet/modules
      name: _usr_share_openstack-puppet_modules___usr_share_openstack-puppet_modules
      readOnly: true
  - command: &id002
    - /usr/bin/bootstrap_host_exec
    - keystone
    - /usr/local/bin/kolla_start
    env:
    - name: KOLLA_BOOTSTRAP
      value: true
    - name: KOLLA_CONFIG_STRATEGY
      value: COPY_ALWAYS
    - name: TRIPLEO_DEPLOY_IDENTIFIER
      value: '1630483989'
    - name: TRIPLEO_CONFIG_HASH
      value: 9cb76b3e64a1db57a5ebca60a5378358
    image: 192.168.24.1:8787/tripleomaster/openstack-keystone:2fa7870e5aa16053f63f8b63df4f955b-updated-20210901075107
    label:
      config_data:
        command: *id002
        detach: false
        environment:
          KOLLA_BOOTSTRAP: true
          KOLLA_CONFIG_STRATEGY: COPY_ALWAYS
          TRIPLEO_CONFIG_HASH: 9cb76b3e64a1db57a5ebca60a5378358
          TRIPLEO_DEPLOY_IDENTIFIER: '1630483989'
        image: 192.168.24.1:8787/tripleomaster/openstack-keystone:2fa7870e5aa16053f63f8b63df4f955b-updated-20210901075107
        net: host
        privileged: false
        user: root
        volumes:
        - /etc/hosts:/etc/hosts:ro
        - /etc/localtime:/etc/localtime:ro
        - /etc/pki/ca-trust/extracted:/etc/pki/ca-trust/extracted:ro
        - /etc/pki/ca-trust/source/anchors:/etc/pki/ca-trust/source/anchors:ro
        - /etc/pki/tls/certs/ca-bundle.crt:/etc/pki/tls/certs/ca-bundle.crt:ro
        - /etc/pki/tls/certs/ca-bundle.trust.crt:/etc/pki/tls/certs/ca-bundle.trust.crt:ro
        - /etc/pki/tls/cert.pem:/etc/pki/tls/cert.pem:ro
        - /dev/log:/dev/log
        - /etc/puppet:/etc/puppet:ro
        - /var/log/containers/keystone:/var/log/keystone:z
        - /var/log/containers/httpd/keystone:/var/log/httpd:z
        - /etc/openldap:/etc/openldap:ro
        - /var/lib/kolla/config_files/keystone.json:/var/lib/kolla/config_files/config.json:ro
        - /var/lib/config-data/puppet-generated/keystone:/var/lib/kolla/config_files/src:ro
      config_id: tripleo_step3
      container_name: keystone_db_sync
      managed_by: tripleo_ansible
      temporary: true
    name: keystone_db_sync
    securityContext:
      allowPrivilegeEscalation: false
      runAsGroup: 0
      runAsUser: 0
    volumeMounts:
    - mountPath: /etc/hosts
      name: _etc_hosts___etc_hosts
      readOnly: true
    - mountPath: /etc/localtime
      name: _etc_localtime___etc_localtime
      readOnly: true
    - mountPath: /etc/pki/ca-trust/extracted
      name: _etc_pki_ca-trust_extracted___etc_pki_ca-trust_extracted
      readOnly: true
    - mountPath: /etc/pki/ca-trust/source/anchors
      name: _etc_pki_ca-trust_source_anchors___etc_pki_ca-trust_source_anchors
      readOnly: true
    - mountPath: /etc/pki/tls/certs/ca-bundle.crt
      name: _etc_pki_tls_certs_ca-bundle.crt___etc_pki_tls_certs_ca-bundle.crt
      readOnly: true
    - mountPath: /etc/pki/tls/certs/ca-bundle.trust.crt
      name: _etc_pki_tls_certs_ca-bundle.trust.crt___etc_pki_tls_certs_ca-bundle.trust.crt
      readOnly: true
    - mountPath: /etc/pki/tls/cert.pem
      name: _etc_pki_tls_cert.pem___etc_pki_tls_cert.pem
      readOnly: true
    - mountPath: /dev/log
      name: _dev_log___dev_log
    - mountPath: /etc/puppet
      name: _etc_puppet___etc_puppet
      readOnly: true
    - mountPath: /var/log/keystone
      name: _var_log_containers_keystone___var_log_keystone
    - mountPath: /var/log/httpd
      name: _var_log_containers_httpd_keystone___var_log_httpd
    - mountPath: /etc/openldap
      name: _etc_openldap___etc_openldap
      readOnly: true
    - mountPath: /var/lib/kolla/config_files/config.json
      name: _var_lib_kolla_config_files_keystone.json___var_lib_kolla_config_files_config.json
      readOnly: true
    - mountPath: /var/lib/kolla/config_files/src
      name: _var_lib_config-data_puppet-generated_keystone___var_lib_kolla_config_files_src
      readOnly: true
  - command: &id003
    - /bin/bash
    - -c
    - chown -R ironic-inspector:ironic-inspector /var/log/ironic-inspector
    image: 192.168.24.1:8787/tripleomaster/openstack-ironic-inspector:2fa7870e5aa16053f63f8b63df4f955b-updated-20210901075107
    label:
      config_data:
        command: *id003
        image: 192.168.24.1:8787/tripleomaster/openstack-ironic-inspector:2fa7870e5aa16053f63f8b63df4f955b-updated-20210901075107
        net: none
        start_order: 0
        user: root
        volumes:
        - /var/log/containers/ironic-inspector:/var/log/ironic-inspector:z
      config_id: tripleo_step3
      container_name: ironic_inspector_init_log
      managed_by: tripleo_ansible
      temporary: true
    name: ironic_inspector_init_log
    securityContext:
      runAsGroup: 0
      runAsUser: 0
    volumeMounts:
    - mountPath: /var/log/ironic-inspector
      name: _var_log_containers_ironic-inspector___var_log_ironic-inspector
  hostNetwork: true
  restartPolicy: Never
  volumes:
  - hostPath:
      path: /etc/hosts
    name: _etc_hosts___etc_hosts
  - hostPath:
      path: /etc/localtime
    name: _etc_localtime___etc_localtime
  - hostPath:
      path: /etc/pki/ca-trust/extracted
    name: _etc_pki_ca-trust_extracted___etc_pki_ca-trust_extracted
  - hostPath:
      path: /etc/pki/ca-trust/source/anchors
    name: _etc_pki_ca-trust_source_anchors___etc_pki_ca-trust_source_anchors
  - hostPath:
      path: /etc/pki/tls/certs/ca-bundle.crt
    name: _etc_pki_tls_certs_ca-bundle.crt___etc_pki_tls_certs_ca-bundle.crt
  - hostPath:
      path: /etc/pki/tls/certs/ca-bundle.trust.crt
    name: _etc_pki_tls_certs_ca-bundle.trust.crt___etc_pki_tls_certs_ca-bundle.trust.crt
  - hostPath:
      path: /etc/pki/tls/cert.pem
    name: _etc_pki_tls_cert.pem___etc_pki_tls_cert.pem
  - hostPath:
      path: /dev/log
    name: _dev_log___dev_log
  - hostPath:
      path: /etc/puppet
    name: _etc_puppet___etc_puppet
  - hostPath:
      path: /var/log/containers/neutron
    name: _var_log_containers_neutron___var_log_neutron
  - hostPath:
      path: /var/log/containers/httpd/neutron-api
    name: _var_log_containers_httpd_neutron-api___var_log_httpd
  - hostPath:
      path: /var/lib/kolla/config_files/neutron_api_db_sync.json
    name: _var_lib_kolla_config_files_neutron_api_db_sync.json___var_lib_kolla_config_files_config.json
  - hostPath:
      path: /var/lib/config-data/puppet-generated/neutron
    name: _var_lib_config-data_puppet-generated_neutron___var_lib_kolla_config_files_src
  - hostPath:
      path: /var/lib/kolla/config_files/neutron_ovs_agent.json
    name: _var_lib_kolla_config_files_neutron_ovs_agent.json___var_lib_kolla_config_files_config.json
  - hostPath:
      path: /lib/modules
    name: _lib_modules___lib_modules
  - hostPath:
      path: /run/openvswitch
    name: _run_openvswitch___run_openvswitch
  - hostPath:
      path: /usr/share/openstack-puppet/modules
    name: _usr_share_openstack-puppet_modules___usr_share_openstack-puppet_modules
  - hostPath:
      path: /var/log/containers/keystone
    name: _var_log_containers_keystone___var_log_keystone
  - hostPath:
      path: /var/log/containers/httpd/keystone
    name: _var_log_containers_httpd_keystone___var_log_httpd
  - hostPath:
      path: /etc/openldap
    name: _etc_openldap___etc_openldap
  - hostPath:
      path: /var/lib/kolla/config_files/keystone.json
    name: _var_lib_kolla_config_files_keystone.json___var_lib_kolla_config_files_config.json
  - hostPath:
      path: /var/lib/config-data/puppet-generated/keystone
    name: _var_lib_config-data_puppet-generated_keystone___var_lib_kolla_config_files_src
  - hostPath:
      path: /var/log/containers/ironic-inspector
    name: _var_log_containers_ironic-inspector___var_log_ironic-inspector
