apiVersion: v1
kind: Pod
metadata:
  labels:
    app: tripleo-step-tripleo_step3
  name: tripleo_step3-step-2
spec:
  containers:
  - env:
    - name: KOLLA_CONFIG_STRATEGY
      value: COPY_ALWAYS
    - name: TRIPLEO_CONFIG_HASH
      value: 9cb76b3e64a1db57a5ebca60a5378358
    image: 192.168.24.1:8787/tripleomaster/openstack-keystone:2fa7870e5aa16053f63f8b63df4f955b-updated-20210901075107
    label:
      config_data:
        environment:
          KOLLA_CONFIG_STRATEGY: COPY_ALWAYS
          TRIPLEO_CONFIG_HASH: 9cb76b3e64a1db57a5ebca60a5378358
        healthcheck:
          test: /openstack/healthcheck
        image: 192.168.24.1:8787/tripleomaster/openstack-keystone:2fa7870e5aa16053f63f8b63df4f955b-updated-20210901075107
        net: host
        privileged: false
        restart: always
        start_order: 2
        volumes:
        - /etc/hosts:/etc/hosts:ro
        - /etc/localtime:/etc/localtime:ro
        - /etc/pki/ca-trust/extracted:/etc/pki/ca-trust/extracted:ro
        - /etc/pki/ca-trust/source/anchors:/etc/pki/ca-trust/source/anchors:ro
        - /etc/pki/tls/certs/ca-bundle.crt:/etc/pki/tls/certs/ca-bundle.crt:ro
        - /etc/pki/tls/certs/ca-bundle.trust.crt:/etc/pki/tls/certs/ca-bundle.trust.crt:ro
        - /etc/pki/tls/cert.pem:/etc/pki/tls/cert.pem:ro
        - /dev/log:/dev/log
        - /etc/puppet:/etc/puppet:ro
        - /var/log/containers/keystone:/var/log/keystone:z
        - /var/log/containers/httpd/keystone:/var/log/httpd:z
        - /etc/openldap:/etc/openldap:ro
        - /var/lib/kolla/config_files/keystone.json:/var/lib/kolla/config_files/config.json:ro
        - /var/lib/config-data/puppet-generated/keystone:/var/lib/kolla/config_files/src:ro
      config_id: tripleo_step3
      container_name: keystone
      managed_by: tripleo_ansible
    name: keystone
    securityContext:
      allowPrivilegeEscalation: false
    volumeMounts:
    - mountPath: /etc/hosts
      name: _etc_hosts___etc_hosts
      readOnly: true
    - mountPath: /etc/localtime
      name: _etc_localtime___etc_localtime
      readOnly: true
    - mountPath: /etc/pki/ca-trust/extracted
      name: _etc_pki_ca-trust_extracted___etc_pki_ca-trust_extracted
      readOnly: true
    - mountPath: /etc/pki/ca-trust/source/anchors
      name: _etc_pki_ca-trust_source_anchors___etc_pki_ca-trust_source_anchors
      readOnly: true
    - mountPath: /etc/pki/tls/certs/ca-bundle.crt
      name: _etc_pki_tls_certs_ca-bundle.crt___etc_pki_tls_certs_ca-bundle.crt
      readOnly: true
    - mountPath: /etc/pki/tls/certs/ca-bundle.trust.crt
      name: _etc_pki_tls_certs_ca-bundle.trust.crt___etc_pki_tls_certs_ca-bundle.trust.crt
      readOnly: true
    - mountPath: /etc/pki/tls/cert.pem
      name: _etc_pki_tls_cert.pem___etc_pki_tls_cert.pem
      readOnly: true
    - mountPath: /dev/log
      name: _dev_log___dev_log
    - mountPath: /etc/puppet
      name: _etc_puppet___etc_puppet
      readOnly: true
    - mountPath: /var/log/keystone
      name: _var_log_containers_keystone___var_log_keystone
    - mountPath: /var/log/httpd
      name: _var_log_containers_httpd_keystone___var_log_httpd
    - mountPath: /etc/openldap
      name: _etc_openldap___etc_openldap
      readOnly: true
    - mountPath: /var/lib/kolla/config_files/config.json
      name: _var_lib_kolla_config_files_keystone.json___var_lib_kolla_config_files_config.json
      readOnly: true
    - mountPath: /var/lib/kolla/config_files/src
      name: _var_lib_config-data_puppet-generated_keystone___var_lib_kolla_config_files_src
      readOnly: true
  - env:
    - name: KOLLA_CONFIG_STRATEGY
      value: COPY_ALWAYS
    - name: TRIPLEO_CONFIG_HASH
      value: 501fa4a57a6c5b95a8c8c55d3dd22add
    image: 192.168.24.1:8787/tripleomaster/openstack-iscsid:2fa7870e5aa16053f63f8b63df4f955b-updated-20210901075107
    label:
      config_data:
        environment:
          KOLLA_CONFIG_STRATEGY: COPY_ALWAYS
          TRIPLEO_CONFIG_HASH: 501fa4a57a6c5b95a8c8c55d3dd22add
        healthcheck:
          test: /openstack/healthcheck
        image: 192.168.24.1:8787/tripleomaster/openstack-iscsid:2fa7870e5aa16053f63f8b63df4f955b-updated-20210901075107
        net: host
        privileged: true
        restart: always
        start_order: 2
        volumes:
        - /etc/hosts:/etc/hosts:ro
        - /etc/localtime:/etc/localtime:ro
        - /etc/pki/ca-trust/extracted:/etc/pki/ca-trust/extracted:ro
        - /etc/pki/ca-trust/source/anchors:/etc/pki/ca-trust/source/anchors:ro
        - /etc/pki/tls/certs/ca-bundle.crt:/etc/pki/tls/certs/ca-bundle.crt:ro
        - /etc/pki/tls/certs/ca-bundle.trust.crt:/etc/pki/tls/certs/ca-bundle.trust.crt:ro
        - /etc/pki/tls/cert.pem:/etc/pki/tls/cert.pem:ro
        - /dev/log:/dev/log
        - /etc/puppet:/etc/puppet:ro
        - /var/lib/kolla/config_files/iscsid.json:/var/lib/kolla/config_files/config.json:ro
        - /dev/:/dev/
        - /run/:/run/
        - /sys:/sys
        - /lib/modules:/lib/modules:ro
        - /var/lib/config-data/puppet-generated/iscsid/etc/iscsi:/var/lib/kolla/config_files/src-iscsid:ro
        - /etc/target:/etc/target:z
        - /var/lib/iscsi:/var/lib/iscsi:z
      config_id: tripleo_step3
      container_name: iscsid
      managed_by: tripleo_ansible
    name: iscsid
    securityContext:
      allowPrivilegeEscalation: true
    volumeMounts:
    - mountPath: /etc/hosts
      name: _etc_hosts___etc_hosts
      readOnly: true
    - mountPath: /etc/localtime
      name: _etc_localtime___etc_localtime
      readOnly: true
    - mountPath: /etc/pki/ca-trust/extracted
      name: _etc_pki_ca-trust_extracted___etc_pki_ca-trust_extracted
      readOnly: true
    - mountPath: /etc/pki/ca-trust/source/anchors
      name: _etc_pki_ca-trust_source_anchors___etc_pki_ca-trust_source_anchors
      readOnly: true
    - mountPath: /etc/pki/tls/certs/ca-bundle.crt
      name: _etc_pki_tls_certs_ca-bundle.crt___etc_pki_tls_certs_ca-bundle.crt
      readOnly: true
    - mountPath: /etc/pki/tls/certs/ca-bundle.trust.crt
      name: _etc_pki_tls_certs_ca-bundle.trust.crt___etc_pki_tls_certs_ca-bundle.trust.crt
      readOnly: true
    - mountPath: /etc/pki/tls/cert.pem
      name: _etc_pki_tls_cert.pem___etc_pki_tls_cert.pem
      readOnly: true
    - mountPath: /dev/log
      name: _dev_log___dev_log
    - mountPath: /etc/puppet
      name: _etc_puppet___etc_puppet
      readOnly: true
    - mountPath: /var/lib/kolla/config_files/config.json
      name: _var_lib_kolla_config_files_iscsid.json___var_lib_kolla_config_files_config.json
      readOnly: true
    - mountPath: /dev
      name: _dev___dev
    - mountPath: /run
      name: _run___run
    - mountPath: /sys
      name: _sys___sys
    - mountPath: /lib/modules
      name: _lib_modules___lib_modules
      readOnly: true
    - mountPath: /var/lib/kolla/config_files/src-iscsid
      name: _var_lib_config-data_puppet-generated_iscsid_etc_iscsi___var_lib_kolla_config_files_src-iscsid
      readOnly: true
    - mountPath: /etc/target
      name: _etc_target___etc_target
    - mountPath: /var/lib/iscsi
      name: _var_lib_iscsi___var_lib_iscsi
  hostNetwork: true
  restartPolicy: Always
  volumes:
  - hostPath:
      path: /etc/hosts
    name: _etc_hosts___etc_hosts
  - hostPath:
      path: /etc/localtime
    name: _etc_localtime___etc_localtime
  - hostPath:
      path: /etc/pki/ca-trust/extracted
    name: _etc_pki_ca-trust_extracted___etc_pki_ca-trust_extracted
  - hostPath:
      path: /etc/pki/ca-trust/source/anchors
    name: _etc_pki_ca-trust_source_anchors___etc_pki_ca-trust_source_anchors
  - hostPath:
      path: /etc/pki/tls/certs/ca-bundle.crt
    name: _etc_pki_tls_certs_ca-bundle.crt___etc_pki_tls_certs_ca-bundle.crt
  - hostPath:
      path: /etc/pki/tls/certs/ca-bundle.trust.crt
    name: _etc_pki_tls_certs_ca-bundle.trust.crt___etc_pki_tls_certs_ca-bundle.trust.crt
  - hostPath:
      path: /etc/pki/tls/cert.pem
    name: _etc_pki_tls_cert.pem___etc_pki_tls_cert.pem
  - hostPath:
      path: /dev/log
    name: _dev_log___dev_log
  - hostPath:
      path: /etc/puppet
    name: _etc_puppet___etc_puppet
  - hostPath:
      path: /var/log/containers/keystone
    name: _var_log_containers_keystone___var_log_keystone
  - hostPath:
      path: /var/log/containers/httpd/keystone
    name: _var_log_containers_httpd_keystone___var_log_httpd
  - hostPath:
      path: /etc/openldap
    name: _etc_openldap___etc_openldap
  - hostPath:
      path: /var/lib/kolla/config_files/keystone.json
    name: _var_lib_kolla_config_files_keystone.json___var_lib_kolla_config_files_config.json
  - hostPath:
      path: /var/lib/config-data/puppet-generated/keystone
    name: _var_lib_config-data_puppet-generated_keystone___var_lib_kolla_config_files_src
  - hostPath:
      path: /var/lib/kolla/config_files/iscsid.json
    name: _var_lib_kolla_config_files_iscsid.json___var_lib_kolla_config_files_config.json
  - hostPath:
      path: /dev
    name: _dev___dev
  - hostPath:
      path: /run
    name: _run___run
  - hostPath:
      path: /sys
    name: _sys___sys
  - hostPath:
      path: /lib/modules
    name: _lib_modules___lib_modules
  - hostPath:
      path: /var/lib/config-data/puppet-generated/iscsid/etc/iscsi
    name: _var_lib_config-data_puppet-generated_iscsid_etc_iscsi___var_lib_kolla_config_files_src-iscsid
  - hostPath:
      path: /etc/target
    name: _etc_target___etc_target
  - hostPath:
      path: /var/lib/iscsi
    name: _var_lib_iscsi___var_lib_iscsi
