apiVersion: v1
kind: Pod
metadata:
  labels:
    app: tripleo-step-tripleo_step2
  name: tripleo_step2-temp-step-1
spec:
  containers:
  - command: &id001
    - /bin/bash
    - -c
    - chown -R placement:placement /var/log/placement
    image: 38.102.83.65:5001/tripleomaster/openstack-placement-api:2fa7870e5aa16053f63f8b63df4f955b
    label:
      config_data:
        command: *id001
        image: 38.102.83.65:5001/tripleomaster/openstack-placement-api:2fa7870e5aa16053f63f8b63df4f955b
        net: none
        start_order: 1
        user: root
        volumes:
        - /var/log/containers/placement:/var/log/placement:z
        - /var/log/containers/httpd/placement:/var/log/httpd:z
      config_id: tripleo_step2
      container_name: placement_init_log
      managed_by: tripleo_ansible
      temporary: true
    name: placement_init_log
    securityContext:
      runAsGroup: 0
      runAsUser: 0
    volumeMounts:
    - mountPath: /var/log/placement
      name: _var_log_containers_placement___var_log_placement
    - mountPath: /var/log/httpd
      name: _var_log_containers_httpd_placement___var_log_httpd
  - command: &id002
    - /bin/bash
    - -c
    - chown -R keystone:keystone /var/log/keystone
    image: 38.102.83.65:5001/tripleomaster/openstack-keystone:2fa7870e5aa16053f63f8b63df4f955b
    label:
      config_data:
        command: *id002
        image: 38.102.83.65:5001/tripleomaster/openstack-keystone:2fa7870e5aa16053f63f8b63df4f955b
        net: none
        start_order: 1
        user: root
        volumes:
        - /var/log/containers/keystone:/var/log/keystone:z
        - /var/log/containers/httpd/keystone:/var/log/httpd:z
      config_id: tripleo_step2
      container_name: keystone_init_log
      managed_by: tripleo_ansible
      temporary: true
    name: keystone_init_log
    securityContext:
      runAsGroup: 0
      runAsUser: 0
    volumeMounts:
    - mountPath: /var/log/keystone
      name: _var_log_containers_keystone___var_log_keystone
    - mountPath: /var/log/httpd
      name: _var_log_containers_httpd_keystone___var_log_httpd
  - command: &id003
    - /container_puppet_apply.sh
    - '4'
    - file
    - include ::tripleo::profile::base::nova::virtlogd_wrapper
    env:
    - name: TRIPLEO_DEPLOY_IDENTIFIER
      value: '1630486528'
    image: 38.102.83.65:5001/tripleomaster/openstack-nova-libvirt:2fa7870e5aa16053f63f8b63df4f955b
    label:
      config_data:
        cgroupns: host
        command: *id003
        detach: false
        environment:
          TRIPLEO_DEPLOY_IDENTIFIER: '1630486528'
        image: 38.102.83.65:5001/tripleomaster/openstack-nova-libvirt:2fa7870e5aa16053f63f8b63df4f955b
        net: host
        pid: host
        start_order: 1
        user: root
        volumes:
        - /etc/hosts:/etc/hosts:ro
        - /etc/localtime:/etc/localtime:ro
        - /etc/pki/ca-trust/extracted:/etc/pki/ca-trust/extracted:ro
        - /etc/pki/ca-trust/source/anchors:/etc/pki/ca-trust/source/anchors:ro
        - /etc/pki/tls/certs/ca-bundle.crt:/etc/pki/tls/certs/ca-bundle.crt:ro
        - /etc/pki/tls/certs/ca-bundle.trust.crt:/etc/pki/tls/certs/ca-bundle.trust.crt:ro
        - /etc/pki/tls/cert.pem:/etc/pki/tls/cert.pem:ro
        - /dev/log:/dev/log
        - /var/lib/container-config-scripts/container_puppet_apply.sh:/container_puppet_apply.sh:ro
        - /etc/puppet:/tmp/puppet-etc:ro
        - /usr/share/openstack-puppet/modules:/usr/share/openstack-puppet/modules:ro
        - /var/lib/container-config-scripts:/var/lib/container-config-scripts:shared,z
      config_id: tripleo_step2
      container_name: create_virtlogd_wrapper
      managed_by: tripleo_ansible
      temporary: true
    name: create_virtlogd_wrapper
    securityContext:
      runAsGroup: 0
      runAsUser: 0
    volumeMounts:
    - mountPath: /etc/hosts
      name: _etc_hosts___etc_hosts
      readOnly: true
    - mountPath: /etc/localtime
      name: _etc_localtime___etc_localtime
      readOnly: true
    - mountPath: /etc/pki/ca-trust/extracted
      name: _etc_pki_ca-trust_extracted___etc_pki_ca-trust_extracted
      readOnly: true
    - mountPath: /etc/pki/ca-trust/source/anchors
      name: _etc_pki_ca-trust_source_anchors___etc_pki_ca-trust_source_anchors
      readOnly: true
    - mountPath: /etc/pki/tls/certs/ca-bundle.crt
      name: _etc_pki_tls_certs_ca-bundle.crt___etc_pki_tls_certs_ca-bundle.crt
      readOnly: true
    - mountPath: /etc/pki/tls/certs/ca-bundle.trust.crt
      name: _etc_pki_tls_certs_ca-bundle.trust.crt___etc_pki_tls_certs_ca-bundle.trust.crt
      readOnly: true
    - mountPath: /etc/pki/tls/cert.pem
      name: _etc_pki_tls_cert.pem___etc_pki_tls_cert.pem
      readOnly: true
    - mountPath: /dev/log
      name: _dev_log___dev_log
    - mountPath: /container_puppet_apply.sh
      name: _var_lib_container-config-scripts_container_puppet_apply.sh___container_puppet_apply.sh
      readOnly: true
    - mountPath: /tmp/puppet-etc
      name: _etc_puppet___tmp_puppet-etc
      readOnly: true
    - mountPath: /usr/share/openstack-puppet/modules
      name: _usr_share_openstack-puppet_modules___usr_share_openstack-puppet_modules
      readOnly: true
    - mountPath: /var/lib/container-config-scripts
      name: _var_lib_container-config-scripts___var_lib_container-config-scripts
  - command: &id004
    - /container_puppet_apply.sh
    - '4'
    - file
    - include ::tripleo::profile::base::neutron::ovn_metadata_agent_wrappers
    image: 38.102.83.65:5001/tripleomaster/openstack-neutron-metadata-agent-ovn:2fa7870e5aa16053f63f8b63df4f955b
    label:
      config_data:
        command: *id004
        detach: false
        image: 38.102.83.65:5001/tripleomaster/openstack-neutron-metadata-agent-ovn:2fa7870e5aa16053f63f8b63df4f955b
        net: host
        pid: host
        start_order: 1
        user: root
        volumes:
        - /etc/hosts:/etc/hosts:ro
        - /etc/localtime:/etc/localtime:ro
        - /etc/pki/ca-trust/extracted:/etc/pki/ca-trust/extracted:ro
        - /etc/pki/ca-trust/source/anchors:/etc/pki/ca-trust/source/anchors:ro
        - /etc/pki/tls/certs/ca-bundle.crt:/etc/pki/tls/certs/ca-bundle.crt:ro
        - /etc/pki/tls/certs/ca-bundle.trust.crt:/etc/pki/tls/certs/ca-bundle.trust.crt:ro
        - /etc/pki/tls/cert.pem:/etc/pki/tls/cert.pem:ro
        - /dev/log:/dev/log
        - /var/lib/container-config-scripts/container_puppet_apply.sh:/container_puppet_apply.sh:ro
        - /etc/puppet:/tmp/puppet-etc:ro
        - /usr/share/openstack-puppet/modules:/usr/share/openstack-puppet/modules:ro
        - /run/openvswitch:/run/openvswitch:shared,z
        - /var/lib/neutron:/var/lib/neutron:shared,z
      config_id: tripleo_step2
      container_name: create_haproxy_wrapper
      managed_by: tripleo_ansible
      temporary: true
    name: create_haproxy_wrapper
    securityContext:
      runAsGroup: 0
      runAsUser: 0
    volumeMounts:
    - mountPath: /etc/hosts
      name: _etc_hosts___etc_hosts
      readOnly: true
    - mountPath: /etc/localtime
      name: _etc_localtime___etc_localtime
      readOnly: true
    - mountPath: /etc/pki/ca-trust/extracted
      name: _etc_pki_ca-trust_extracted___etc_pki_ca-trust_extracted
      readOnly: true
    - mountPath: /etc/pki/ca-trust/source/anchors
      name: _etc_pki_ca-trust_source_anchors___etc_pki_ca-trust_source_anchors
      readOnly: true
    - mountPath: /etc/pki/tls/certs/ca-bundle.crt
      name: _etc_pki_tls_certs_ca-bundle.crt___etc_pki_tls_certs_ca-bundle.crt
      readOnly: true
    - mountPath: /etc/pki/tls/certs/ca-bundle.trust.crt
      name: _etc_pki_tls_certs_ca-bundle.trust.crt___etc_pki_tls_certs_ca-bundle.trust.crt
      readOnly: true
    - mountPath: /etc/pki/tls/cert.pem
      name: _etc_pki_tls_cert.pem___etc_pki_tls_cert.pem
      readOnly: true
    - mountPath: /dev/log
      name: _dev_log___dev_log
    - mountPath: /container_puppet_apply.sh
      name: _var_lib_container-config-scripts_container_puppet_apply.sh___container_puppet_apply.sh
      readOnly: true
    - mountPath: /tmp/puppet-etc
      name: _etc_puppet___tmp_puppet-etc
      readOnly: true
    - mountPath: /usr/share/openstack-puppet/modules
      name: _usr_share_openstack-puppet_modules___usr_share_openstack-puppet_modules
      readOnly: true
    - mountPath: /run/openvswitch
      name: _run_openvswitch___run_openvswitch
    - mountPath: /var/lib/neutron
      name: _var_lib_neutron___var_lib_neutron
  hostNetwork: true
  restartPolicy: Never
  volumes:
  - hostPath:
      path: /var/log/containers/placement
    name: _var_log_containers_placement___var_log_placement
  - hostPath:
      path: /var/log/containers/httpd/placement
    name: _var_log_containers_httpd_placement___var_log_httpd
  - hostPath:
      path: /var/log/containers/keystone
    name: _var_log_containers_keystone___var_log_keystone
  - hostPath:
      path: /var/log/containers/httpd/keystone
    name: _var_log_containers_httpd_keystone___var_log_httpd
  - hostPath:
      path: /etc/hosts
    name: _etc_hosts___etc_hosts
  - hostPath:
      path: /etc/localtime
    name: _etc_localtime___etc_localtime
  - hostPath:
      path: /etc/pki/ca-trust/extracted
    name: _etc_pki_ca-trust_extracted___etc_pki_ca-trust_extracted
  - hostPath:
      path: /etc/pki/ca-trust/source/anchors
    name: _etc_pki_ca-trust_source_anchors___etc_pki_ca-trust_source_anchors
  - hostPath:
      path: /etc/pki/tls/certs/ca-bundle.crt
    name: _etc_pki_tls_certs_ca-bundle.crt___etc_pki_tls_certs_ca-bundle.crt
  - hostPath:
      path: /etc/pki/tls/certs/ca-bundle.trust.crt
    name: _etc_pki_tls_certs_ca-bundle.trust.crt___etc_pki_tls_certs_ca-bundle.trust.crt
  - hostPath:
      path: /etc/pki/tls/cert.pem
    name: _etc_pki_tls_cert.pem___etc_pki_tls_cert.pem
  - hostPath:
      path: /dev/log
    name: _dev_log___dev_log
  - hostPath:
      path: /var/lib/container-config-scripts/container_puppet_apply.sh
    name: _var_lib_container-config-scripts_container_puppet_apply.sh___container_puppet_apply.sh
  - hostPath:
      path: /etc/puppet
    name: _etc_puppet___tmp_puppet-etc
  - hostPath:
      path: /usr/share/openstack-puppet/modules
    name: _usr_share_openstack-puppet_modules___usr_share_openstack-puppet_modules
  - hostPath:
      path: /var/lib/container-config-scripts
    name: _var_lib_container-config-scripts___var_lib_container-config-scripts
  - hostPath:
      path: /run/openvswitch
    name: _run_openvswitch___run_openvswitch
  - hostPath:
      path: /var/lib/neutron
    name: _var_lib_neutron___var_lib_neutron
