apiVersion: v1
kind: Pod
metadata:
  labels:
    app: tripleo-step-tripleo_step3
  name: tripleo_step3-step-0
spec:
  containers:
  - env:
    - name: KOLLA_CONFIG_STRATEGY
      value: COPY_ALWAYS
    - name: TRIPLEO_CONFIG_HASH
      value: 4d1b89d476636748267f959151a9bca6
    image: 38.102.83.65:5001/tripleomaster/openstack-nova-libvirt:2fa7870e5aa16053f63f8b63df4f955b
    label:
      config_data:
        cgroupns: host
        environment:
          KOLLA_CONFIG_STRATEGY: COPY_ALWAYS
          TRIPLEO_CONFIG_HASH: 4d1b89d476636748267f959151a9bca6
        healthcheck:
          test: /openstack/healthcheck virtlogd
        image: 38.102.83.65:5001/tripleomaster/openstack-nova-libvirt:2fa7870e5aa16053f63f8b63df4f955b
        net: host
        pid: host
        privileged: true
        restart: always
        security_opt:
        - label=disable
        start_order: 0
        ulimit:
        - nofile=131072
        - nproc=126960
        volumes:
        - /etc/hosts:/etc/hosts:ro
        - /etc/localtime:/etc/localtime:ro
        - /etc/pki/ca-trust/extracted:/etc/pki/ca-trust/extracted:ro
        - /etc/pki/ca-trust/source/anchors:/etc/pki/ca-trust/source/anchors:ro
        - /etc/pki/tls/certs/ca-bundle.crt:/etc/pki/tls/certs/ca-bundle.crt:ro
        - /etc/pki/tls/certs/ca-bundle.trust.crt:/etc/pki/tls/certs/ca-bundle.trust.crt:ro
        - /etc/pki/tls/cert.pem:/etc/pki/tls/cert.pem:ro
        - /dev/log:/dev/log
        - /etc/puppet:/etc/puppet:ro
        - /var/log/containers/libvirt:/var/log/libvirt:z
        - /var/lib/kolla/config_files/nova_virtlogd.json:/var/lib/kolla/config_files/config.json:ro
        - /var/lib/config-data/puppet-generated/nova_libvirt:/var/lib/kolla/config_files/src:ro
        - /lib/modules:/lib/modules:ro
        - /dev:/dev
        - /run:/run
        - /sys/fs/cgroup:/sys/fs/cgroup
        - /run/libvirt:/run/libvirt:shared
        - /var/lib/libvirt:/var/lib/libvirt
        - /etc/libvirt/qemu:/etc/libvirt/qemu:ro
        - /var/log/libvirt/qemu:/var/log/libvirt/qemu
        - /var/lib/nova:/var/lib/nova:shared
        - /var/lib/container-config-scripts/virtlogd_wrapper:/usr/local/bin/virtlogd_wrapper:ro
      config_id: tripleo_step3
      container_name: nova_virtlogd_wrapper
      managed_by: tripleo_ansible
    name: nova_virtlogd_wrapper
    securityContext:
      allowPrivilegeEscalation: true
    volumeMounts:
    - mountPath: /etc/hosts
      name: _etc_hosts___etc_hosts
      readOnly: true
    - mountPath: /etc/localtime
      name: _etc_localtime___etc_localtime
      readOnly: true
    - mountPath: /etc/pki/ca-trust/extracted
      name: _etc_pki_ca-trust_extracted___etc_pki_ca-trust_extracted
      readOnly: true
    - mountPath: /etc/pki/ca-trust/source/anchors
      name: _etc_pki_ca-trust_source_anchors___etc_pki_ca-trust_source_anchors
      readOnly: true
    - mountPath: /etc/pki/tls/certs/ca-bundle.crt
      name: _etc_pki_tls_certs_ca-bundle.crt___etc_pki_tls_certs_ca-bundle.crt
      readOnly: true
    - mountPath: /etc/pki/tls/certs/ca-bundle.trust.crt
      name: _etc_pki_tls_certs_ca-bundle.trust.crt___etc_pki_tls_certs_ca-bundle.trust.crt
      readOnly: true
    - mountPath: /etc/pki/tls/cert.pem
      name: _etc_pki_tls_cert.pem___etc_pki_tls_cert.pem
      readOnly: true
    - mountPath: /dev/log
      name: _dev_log___dev_log
    - mountPath: /etc/puppet
      name: _etc_puppet___etc_puppet
      readOnly: true
    - mountPath: /var/log/libvirt
      name: _var_log_containers_libvirt___var_log_libvirt
    - mountPath: /var/lib/kolla/config_files/config.json
      name: _var_lib_kolla_config_files_nova_virtlogd.json___var_lib_kolla_config_files_config.json
      readOnly: true
    - mountPath: /var/lib/kolla/config_files/src
      name: _var_lib_config-data_puppet-generated_nova_libvirt___var_lib_kolla_config_files_src
      readOnly: true
    - mountPath: /lib/modules
      name: _lib_modules___lib_modules
      readOnly: true
    - mountPath: /dev
      name: _dev___dev
    - mountPath: /run
      name: _run___run
    - mountPath: /sys/fs/cgroup
      name: _sys_fs_cgroup___sys_fs_cgroup
    - mountPath: /run/libvirt
      name: _run_libvirt___run_libvirt
    - mountPath: /var/lib/libvirt
      name: _var_lib_libvirt___var_lib_libvirt
    - mountPath: /etc/libvirt/qemu
      name: _etc_libvirt_qemu___etc_libvirt_qemu
      readOnly: true
    - mountPath: /var/log/libvirt/qemu
      name: _var_log_libvirt_qemu___var_log_libvirt_qemu
    - mountPath: /var/lib/nova
      name: _var_lib_nova___var_lib_nova
    - mountPath: /usr/local/bin/virtlogd_wrapper
      name: _var_lib_container-config-scripts_virtlogd_wrapper___usr_local_bin_virtlogd_wrapper
      readOnly: true
  - env:
    - name: ENABLE_HEAT
      value: 'yes'
    - name: ENABLE_IRONIC
      value: 'yes'
    - name: ENABLE_MANILA
      value: 'yes'
    - name: ENABLE_OCTAVIA
      value: 'yes'
    - name: KOLLA_CONFIG_STRATEGY
      value: COPY_ALWAYS
    - name: TRIPLEO_CONFIG_HASH
      value: 5a18f1016ad5534fde6be25745928837
    image: 38.102.83.65:5001/tripleomaster/openstack-horizon:2fa7870e5aa16053f63f8b63df4f955b
    label:
      config_data:
        environment:
          ENABLE_HEAT: 'yes'
          ENABLE_IRONIC: 'yes'
          ENABLE_MANILA: 'yes'
          ENABLE_OCTAVIA: 'yes'
          KOLLA_CONFIG_STRATEGY: COPY_ALWAYS
          TRIPLEO_CONFIG_HASH: 5a18f1016ad5534fde6be25745928837
        healthcheck:
          test: /openstack/healthcheck
        image: 38.102.83.65:5001/tripleomaster/openstack-horizon:2fa7870e5aa16053f63f8b63df4f955b
        net: host
        privileged: false
        restart: always
        volumes:
        - /etc/hosts:/etc/hosts:ro
        - /etc/localtime:/etc/localtime:ro
        - /etc/pki/ca-trust/extracted:/etc/pki/ca-trust/extracted:ro
        - /etc/pki/ca-trust/source/anchors:/etc/pki/ca-trust/source/anchors:ro
        - /etc/pki/tls/certs/ca-bundle.crt:/etc/pki/tls/certs/ca-bundle.crt:ro
        - /etc/pki/tls/certs/ca-bundle.trust.crt:/etc/pki/tls/certs/ca-bundle.trust.crt:ro
        - /etc/pki/tls/cert.pem:/etc/pki/tls/cert.pem:ro
        - /dev/log:/dev/log
        - /etc/puppet:/etc/puppet:ro
        - /var/lib/kolla/config_files/horizon.json:/var/lib/kolla/config_files/config.json:ro
        - /var/lib/config-data/puppet-generated/horizon:/var/lib/kolla/config_files/src:ro
        - /var/log/containers/horizon:/var/log/horizon:z
        - /var/log/containers/httpd/horizon:/var/log/httpd:z
        - /var/tmp/horizon:/var/tmp/:z
        - /var/www/:/var/www/:ro
      config_id: tripleo_step3
      container_name: horizon
      managed_by: tripleo_ansible
    name: horizon
    securityContext:
      allowPrivilegeEscalation: false
    volumeMounts:
    - mountPath: /etc/hosts
      name: _etc_hosts___etc_hosts
      readOnly: true
    - mountPath: /etc/localtime
      name: _etc_localtime___etc_localtime
      readOnly: true
    - mountPath: /etc/pki/ca-trust/extracted
      name: _etc_pki_ca-trust_extracted___etc_pki_ca-trust_extracted
      readOnly: true
    - mountPath: /etc/pki/ca-trust/source/anchors
      name: _etc_pki_ca-trust_source_anchors___etc_pki_ca-trust_source_anchors
      readOnly: true
    - mountPath: /etc/pki/tls/certs/ca-bundle.crt
      name: _etc_pki_tls_certs_ca-bundle.crt___etc_pki_tls_certs_ca-bundle.crt
      readOnly: true
    - mountPath: /etc/pki/tls/certs/ca-bundle.trust.crt
      name: _etc_pki_tls_certs_ca-bundle.trust.crt___etc_pki_tls_certs_ca-bundle.trust.crt
      readOnly: true
    - mountPath: /etc/pki/tls/cert.pem
      name: _etc_pki_tls_cert.pem___etc_pki_tls_cert.pem
      readOnly: true
    - mountPath: /dev/log
      name: _dev_log___dev_log
    - mountPath: /etc/puppet
      name: _etc_puppet___etc_puppet
      readOnly: true
    - mountPath: /var/lib/kolla/config_files/config.json
      name: _var_lib_kolla_config_files_horizon.json___var_lib_kolla_config_files_config.json
      readOnly: true
    - mountPath: /var/lib/kolla/config_files/src
      name: _var_lib_config-data_puppet-generated_horizon___var_lib_kolla_config_files_src
      readOnly: true
    - mountPath: /var/log/horizon
      name: _var_log_containers_horizon___var_log_horizon
    - mountPath: /var/log/httpd
      name: _var_log_containers_httpd_horizon___var_log_httpd
    - mountPath: /var/tmp
      name: _var_tmp_horizon___var_tmp
    - mountPath: /var/www
      name: _var_www___var_www
      readOnly: true
  hostNetwork: true
  restartPolicy: Always
  volumes:
  - hostPath:
      path: /etc/hosts
    name: _etc_hosts___etc_hosts
  - hostPath:
      path: /etc/localtime
    name: _etc_localtime___etc_localtime
  - hostPath:
      path: /etc/pki/ca-trust/extracted
    name: _etc_pki_ca-trust_extracted___etc_pki_ca-trust_extracted
  - hostPath:
      path: /etc/pki/ca-trust/source/anchors
    name: _etc_pki_ca-trust_source_anchors___etc_pki_ca-trust_source_anchors
  - hostPath:
      path: /etc/pki/tls/certs/ca-bundle.crt
    name: _etc_pki_tls_certs_ca-bundle.crt___etc_pki_tls_certs_ca-bundle.crt
  - hostPath:
      path: /etc/pki/tls/certs/ca-bundle.trust.crt
    name: _etc_pki_tls_certs_ca-bundle.trust.crt___etc_pki_tls_certs_ca-bundle.trust.crt
  - hostPath:
      path: /etc/pki/tls/cert.pem
    name: _etc_pki_tls_cert.pem___etc_pki_tls_cert.pem
  - hostPath:
      path: /dev/log
    name: _dev_log___dev_log
  - hostPath:
      path: /etc/puppet
    name: _etc_puppet___etc_puppet
  - hostPath:
      path: /var/log/containers/libvirt
    name: _var_log_containers_libvirt___var_log_libvirt
  - hostPath:
      path: /var/lib/kolla/config_files/nova_virtlogd.json
    name: _var_lib_kolla_config_files_nova_virtlogd.json___var_lib_kolla_config_files_config.json
  - hostPath:
      path: /var/lib/config-data/puppet-generated/nova_libvirt
    name: _var_lib_config-data_puppet-generated_nova_libvirt___var_lib_kolla_config_files_src
  - hostPath:
      path: /lib/modules
    name: _lib_modules___lib_modules
  - hostPath:
      path: /dev
    name: _dev___dev
  - hostPath:
      path: /run
    name: _run___run
  - hostPath:
      path: /sys/fs/cgroup
    name: _sys_fs_cgroup___sys_fs_cgroup
  - hostPath:
      path: /run/libvirt
    name: _run_libvirt___run_libvirt
  - hostPath:
      path: /var/lib/libvirt
    name: _var_lib_libvirt___var_lib_libvirt
  - hostPath:
      path: /etc/libvirt/qemu
    name: _etc_libvirt_qemu___etc_libvirt_qemu
  - hostPath:
      path: /var/log/libvirt/qemu
    name: _var_log_libvirt_qemu___var_log_libvirt_qemu
  - hostPath:
      path: /var/lib/nova
    name: _var_lib_nova___var_lib_nova
  - hostPath:
      path: /var/lib/container-config-scripts/virtlogd_wrapper
    name: _var_lib_container-config-scripts_virtlogd_wrapper___usr_local_bin_virtlogd_wrapper
  - hostPath:
      path: /var/lib/kolla/config_files/horizon.json
    name: _var_lib_kolla_config_files_horizon.json___var_lib_kolla_config_files_config.json
  - hostPath:
      path: /var/lib/config-data/puppet-generated/horizon
    name: _var_lib_config-data_puppet-generated_horizon___var_lib_kolla_config_files_src
  - hostPath:
      path: /var/log/containers/horizon
    name: _var_log_containers_horizon___var_log_horizon
  - hostPath:
      path: /var/log/containers/httpd/horizon
    name: _var_log_containers_httpd_horizon___var_log_httpd
  - hostPath:
      path: /var/tmp/horizon
    name: _var_tmp_horizon___var_tmp
  - hostPath:
      path: /var/www
    name: _var_www___var_www
