apiVersion: v1
kind: Pod
metadata:
  labels:
    app: tripleo-step-tripleo_step1
  name: tripleo_step1-temp-step-1
spec:
  containers:
  - command: &id001
    - bash
    - -ec
    - 'if [ -e /var/lib/mysql/mysql ]; then exit 0; fi

      echo -e "\n[mysqld]\nwsrep_provider=none" >> /etc/my.cnf

      kolla_set_configs

      sudo -u mysql -E kolla_extend_start

      timeout ${DB_MAX_TIMEOUT} /bin/bash -c ''while pgrep -af /usr/bin/mysqld_safe
      | grep -q -v grep; do sleep 1; done''

      mysqld_safe --skip-networking --wsrep-on=OFF &

      timeout ${DB_MAX_TIMEOUT} /bin/bash -c ''until mysqladmin -uroot -p"${DB_ROOT_PASSWORD}"
      ping 2>/dev/null; do sleep 1; done''

      mysql -uroot -p"${DB_ROOT_PASSWORD}" -e "CREATE USER ''clustercheck''@''localhost''
      IDENTIFIED BY ''${DB_CLUSTERCHECK_PASSWORD}'';"

      mysql -uroot -p"${DB_ROOT_PASSWORD}" -e "GRANT PROCESS ON *.* TO ''clustercheck''@''localhost''
      WITH GRANT OPTION;"

      mysql -uroot -p"${DB_ROOT_PASSWORD}" -e "DELETE FROM mysql.user WHERE user =
      ''root'' AND host NOT IN (''%'',''localhost'');"

      timeout ${DB_MAX_TIMEOUT} mysqladmin -uroot -p"${DB_ROOT_PASSWORD}" shutdown'
    env:
    - name: DB_CLUSTERCHECK_PASSWORD
      value: 8FjeqjI4P1tINBWEgLJyw91lm
    - name: DB_MAX_TIMEOUT
      value: 60
    - name: DB_ROOT_PASSWORD
      value: X1uuL0Vq9E
    - name: KOLLA_BOOTSTRAP
      value: true
    - name: KOLLA_CONFIG_STRATEGY
      value: COPY_ALWAYS
    - name: TRIPLEO_CONFIG_HASH
      value: 177f9f3f1d4fd427ca26e6375aa2b787
    image: 38.102.83.65:5001/tripleomaster/openstack-mariadb:2fa7870e5aa16053f63f8b63df4f955b
    label:
      config_data:
        command: *id001
        detach: false
        environment:
          DB_CLUSTERCHECK_PASSWORD: 8FjeqjI4P1tINBWEgLJyw91lm
          DB_MAX_TIMEOUT: 60
          DB_ROOT_PASSWORD: X1uuL0Vq9E
          KOLLA_BOOTSTRAP: true
          KOLLA_CONFIG_STRATEGY: COPY_ALWAYS
          TRIPLEO_CONFIG_HASH: 177f9f3f1d4fd427ca26e6375aa2b787
        image: 38.102.83.65:5001/tripleomaster/openstack-mariadb:2fa7870e5aa16053f63f8b63df4f955b
        net: host
        start_order: 1
        user: root
        volumes:
        - /etc/hosts:/etc/hosts:ro
        - /etc/localtime:/etc/localtime:ro
        - /etc/pki/ca-trust/extracted:/etc/pki/ca-trust/extracted:ro
        - /etc/pki/ca-trust/source/anchors:/etc/pki/ca-trust/source/anchors:ro
        - /etc/pki/tls/certs/ca-bundle.crt:/etc/pki/tls/certs/ca-bundle.crt:ro
        - /etc/pki/tls/certs/ca-bundle.trust.crt:/etc/pki/tls/certs/ca-bundle.trust.crt:ro
        - /etc/pki/tls/cert.pem:/etc/pki/tls/cert.pem:ro
        - /dev/log:/dev/log
        - /etc/puppet:/etc/puppet:ro
        - /var/lib/kolla/config_files/mysql.json:/var/lib/kolla/config_files/config.json:rw,z
        - /var/lib/config-data/puppet-generated/mysql:/var/lib/kolla/config_files/src:ro,z
        - /var/lib/mysql:/var/lib/mysql:rw,z
      config_id: tripleo_step1
      container_name: mysql_bootstrap
      managed_by: tripleo_ansible
      temporary: true
    name: mysql_bootstrap
    securityContext:
      runAsGroup: 0
      runAsUser: 0
    volumeMounts:
    - mountPath: /etc/hosts
      name: _etc_hosts___etc_hosts
      readOnly: true
    - mountPath: /etc/localtime
      name: _etc_localtime___etc_localtime
      readOnly: true
    - mountPath: /etc/pki/ca-trust/extracted
      name: _etc_pki_ca-trust_extracted___etc_pki_ca-trust_extracted
      readOnly: true
    - mountPath: /etc/pki/ca-trust/source/anchors
      name: _etc_pki_ca-trust_source_anchors___etc_pki_ca-trust_source_anchors
      readOnly: true
    - mountPath: /etc/pki/tls/certs/ca-bundle.crt
      name: _etc_pki_tls_certs_ca-bundle.crt___etc_pki_tls_certs_ca-bundle.crt
      readOnly: true
    - mountPath: /etc/pki/tls/certs/ca-bundle.trust.crt
      name: _etc_pki_tls_certs_ca-bundle.trust.crt___etc_pki_tls_certs_ca-bundle.trust.crt
      readOnly: true
    - mountPath: /etc/pki/tls/cert.pem
      name: _etc_pki_tls_cert.pem___etc_pki_tls_cert.pem
      readOnly: true
    - mountPath: /dev/log
      name: _dev_log___dev_log
    - mountPath: /etc/puppet
      name: _etc_puppet___etc_puppet
      readOnly: true
    - mountPath: /var/lib/kolla/config_files/config.json
      name: _var_lib_kolla_config_files_mysql.json___var_lib_kolla_config_files_config.json
    - mountPath: /var/lib/kolla/config_files/src
      name: _var_lib_config-data_puppet-generated_mysql___var_lib_kolla_config_files_src
      readOnly: true
    - mountPath: /var/lib/mysql
      name: _var_lib_mysql___var_lib_mysql
  hostNetwork: true
  restartPolicy: Never
  volumes:
  - hostPath:
      path: /etc/hosts
    name: _etc_hosts___etc_hosts
  - hostPath:
      path: /etc/localtime
    name: _etc_localtime___etc_localtime
  - hostPath:
      path: /etc/pki/ca-trust/extracted
    name: _etc_pki_ca-trust_extracted___etc_pki_ca-trust_extracted
  - hostPath:
      path: /etc/pki/ca-trust/source/anchors
    name: _etc_pki_ca-trust_source_anchors___etc_pki_ca-trust_source_anchors
  - hostPath:
      path: /etc/pki/tls/certs/ca-bundle.crt
    name: _etc_pki_tls_certs_ca-bundle.crt___etc_pki_tls_certs_ca-bundle.crt
  - hostPath:
      path: /etc/pki/tls/certs/ca-bundle.trust.crt
    name: _etc_pki_tls_certs_ca-bundle.trust.crt___etc_pki_tls_certs_ca-bundle.trust.crt
  - hostPath:
      path: /etc/pki/tls/cert.pem
    name: _etc_pki_tls_cert.pem___etc_pki_tls_cert.pem
  - hostPath:
      path: /dev/log
    name: _dev_log___dev_log
  - hostPath:
      path: /etc/puppet
    name: _etc_puppet___etc_puppet
  - hostPath:
      path: /var/lib/kolla/config_files/mysql.json
    name: _var_lib_kolla_config_files_mysql.json___var_lib_kolla_config_files_config.json
  - hostPath:
      path: /var/lib/config-data/puppet-generated/mysql
    name: _var_lib_config-data_puppet-generated_mysql___var_lib_kolla_config_files_src
  - hostPath:
      path: /var/lib/mysql
    name: _var_lib_mysql___var_lib_mysql
